### ISSUE TITLE
Support CRUD operation for alarm comment using python CE/PE rest clients

### ISSUE THREAD

**Issue by dashevchenko** [thingsboard/thingsboard-python-rest-client#101]
CE: https://github.com/thingsboard/thingsboard/pull/7762
PE: https://github.com/thingsboard/thingsboard-pe/pull/1362
After mentioned pull requests will be merged we need to add possibility add/update/delete alarm comments using python clients.

**Comment by samson0v** [comment]
Hi @dashevchenko, please, update me on when this feature will be merged so I can add it to REST Client.
