### ISSUE TITLE
Add new REST API method getEdgeDockerInstallInstructions

### ISSUE THREAD

**Issue by volodymyr-babak** [thingsboard/thingsboard-python-rest-client#102]
Please add support of new REST API call according to this diff:
https://github.com/thingsboard/thingsboard/pull/7878/files#diff-6a44826c0ea6e779de6ea5ad49122ca772c0e7b1d18cc5a66d954b525bbc34fc

**Comment by samson0v** [comment]
Hi @volodymyr-babak, please, update me on when this feature will be merged so I can add it to REST Client.
Also, when it is merged, please send me, a swagger file that can be downloaded from (for CE and PE, depending on where feature was added):
<img width="1177" alt="зображення" src="https://user-images.githubusercontent.com/43861229/210960139-3de3c20b-043b-44c4-b5b0-6789191fea74.png">

**Comment by volodymyr-babak** [comment]
@samson0v 

feature is merged.
Feature added into CE and PE.
Attaching swagger file from PE version:
[api-docs.zip](https://github.com/thingsboard/thingsboard-python-rest-client/files/10456266/api-docs.zip)
