### ISSUE TITLE
Unable to save device on on thingsboard cloud.

### ISSUE THREAD

**Issue by FeliceSchena** [thingsboard/thingsboard-python-rest-client#106]
As the docs say, create a new device should be something like this:
`       device = Device(name="Thermometer", type="thermometer",device_profile_id="c8c79e20-*")
        rest_client.save_device(device)`
Unfortunately the save method return

`HTTP response headers: HTTPHeaderDict({'vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'x-content-type-options': 'nosniff', 'x-xss-protection': '1; mode=block', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': '0', 'content-type': 'application/json;charset=ISO-8859-1', 'content-length': '415', 'date': 'Sun, 05 Feb 2023 13:54:49 GMT'})
HTTP response body: b'{"message":"JSON parse error: (was java.lang.ClassCastException); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.ClassCastException) (through reference chain: org.thingsboard.server.common.data.Device[\\"deviceProfileId\\"])","errorCode":2,"status":500,"subscriptionErrorCode":null,"subscriptionEntry":null,"subscriptionValue":null,"timestamp":"2023-02-05T13:54:49.859+00:00"}'`

**Comment by yusufkilany47** [comment]
I still the same problem, how did you fix it ?
