### ISSUE TITLE
[BUG] EntityRelationInfo "from" is deserialized as a protected attribute

### ISSUE THREAD

**Issue by tacensTECSOL** [thingsboard/thingsboard-python-rest-client#110]
Thingsboard version: 3.4.4PE
tb-rest-client version: commit eba3d2c

sample code:
```python
user_id = UserId(id="my user id", entity_type="USER")
query = EntityRelationsQuery(
    filters=[],
    parameters=RelationsSearchParameters(
        root_id=user_id.id,
        root_type=user_id.entity_type,
        direction="FROM",
    )
)
raw_data = tb.entity_relation_controller.find_info_by_query_using_post(body=query, _preload_content=False)
data = tb.find_info_by_query(query)
```

Here is EntityRelationInfo according to the latest swagger doc
![image](https://user-images.githubusercontent.com/109336634/219594780-1f33500d-4525-4b95-b7d4-83a810a9f07f.png)

Here is a response deserialized manually:
![image](https://user-images.githubusercontent.com/109336634/219597170-70e0374f-b85c-4051-9f00-bf1db31aff11.png)

Here is a response deserialized automatically:
![image](https://user-images.githubusercontent.com/109336634/219597907-2846314a-6416-462c-9d88-e30f8e40c842.png)

"from" gets automatically deserialized as a protected attribute (leading underscore).

Is this intentional ?

**Comment by samson0v** [comment]
Hi @tacensTECSOL, thanks for your interest in TB Python REST Client!
Yes, it is intentional, because it is a reserved keyword in Python (from ... import ...).

**Comment by tacensTECSOL** [comment]
Hi, 
Thanks for the clarification !
