### ISSUE TITLE
save_ota_package_data_using_post_with_http_info() got multiple values for argument 'checksum_algorithm'

### ISSUE THREAD

**Issue by dbeulen** [thingsboard/thingsboard-python-rest-client#115]
Hi, i get the following error when trying to use saveOtaPackageData through the python rest client. 

Version:
Thingsboard: v3.4.4
Python rest client: 1.5

In my opinion https://github.com/thingsboard/thingsboard-python-rest-client/blob/3c9f4325c9908d749aec25b4b0332c692bf8f70e/tb_rest_client/api/api_ce/ota_package_controller_api.py#L686  should be changed from:
`def save_ota_package_data_using_post_with_http_info(self, checksum_algorithm, ota_package_id, **kwargs):  # noqa: E501`
TO:
`def save_ota_package_data_using_post_with_http_info(self, ota_package_id, **kwargs):  # noqa: E501`

```
Traceback (most recent call last):
  File "C:\proj\***\uploadFirmware.py", line 49, in <module>
    send_file(sys.argv[1], sys.argv[2], sys.argv[3])
  File "C:\proj\***\uploadFirmware.py", line 38, in send_file
    rest_client.save_ota_package_data(ota_package_id=result.id, checksum_algorithm="SHA256", file=FilePath)
  File "C:\python39\lib\site-packages\tb_rest_client\rest_client_ce.py", line 1515, in save_ota_package_data
    return self.ota_package_controller.save_ota_package_data_using_post(ota_package_id=ota_package_id,
  File "C:\python39\lib\site-packages\tb_rest_client\api\api_ce\ota_package_controller_api.py", line 683, in save_ota_package_data_using_post
    (data) = self.save_ota_package_data_using_post_with_http_info(ota_package_id, **kwargs)  # noqa: E501
TypeError: save_ota_package_data_using_post_with_http_info() got multiple values for argument 'checksum_algorithm'
```

**Comment by samson0v** [comment]
Hi @dbeulen, this bug was fixed, please, use version from the master branch.
