### ISSUE TITLE
Incorrect parsing of "Device" json data

### ISSUE THREAD

**Issue by mentalmod** [thingsboard/thingsboard-python-rest-client#13]
The json data, containing device data, returned by the device_controller functions (for example get_tenant_device, get_customer_devices, etc..) is not being mappedn/parsed correctly to a Device class. That is because of the function ___deserialie(self, data, klass)_ of the class  ApiClient (api_client.py), which cannot determine the correct class to which to desiarilize:

```python
...
                    found_class = getattr(tb_rest_client.models.models_pe, klass)
                    # if sorted(list(found_class.attribute_map.values())) == sorted(list(data.keys())):
                    if all(attr in list(found_class.attribute_map.values()) for attr in list(data.keys())):
                        klass = found_class
```

Here the code is unable to match the attributes of the model class to those of the pre-parsed data and thus is not able to parse it further to Device class, using the ___deserialize_data_,which should call ___deserialize_model_ with klass from type Device, but calls it with type "string" instead ('Device')

TB Version is 3.2.1

**Comment by samson0v** [comment]
Hi @mentalmod, your issue was fixed, please update the rest-client to the newest version (1.3) via master branch or pip.
Thanks for your interest in tb-rest-client!
