### ISSUE TITLE
Error when trying to get RuleChainMetadata

### ISSUE THREAD

**Issue by JRod** [thingsboard/thingsboard-python-rest-client#140]
i run into an error, when I try to get Metadata for a Rulechain with get_rule_chain_meta_data()

` 
try:
                metadata = rest_client.get_rule_chain_meta_data(rc.id.id)
except ValueError as ve:
                logging.debug("value Error %r", ve)`

Invalid value for `rule_chain_connections`, must not be `None`

**Comment by ZutJoe** [comment]
Hello, have you solved this problem? I also encountered this problem. Can you give me some advice, thanks
