### ISSUE TITLE
503 error for rest_client.get_attributes

### ISSUE THREAD

**Issue by dhaval2017** [thingsboard/thingsboard-python-rest-client#16]
Trying get attributes of customer entity
none of below working

customerId=CustomerId("CUSTOMER","bcba4d70-e778-11eb-93f6-e9c8947e0202")
rest_client.get_attributes(entity_id=customerId,kwargs='{"keys":"asdf"}')
or 
customerId=CustomerId("CUSTOMER","bcba4d70-e778-11eb-93f6-e9c8947e0202")
rest_client.get_attributes(entity_id=customerId,kwargs='{"keys":"asdf"}')

gives 503 error
what is right way to call get_attributes for tb_rest_client32.rest_client_ce?

Thanks

**Comment by dhaval2017** [comment]
telemetry_controller_api.py

updated from 

`for key, val in six.iteritems(params['kwargs']):
            params[key] = val`
to 

`for key, val in six.iteritems(params['kwargs']['kwargs']):
            params[key] = val`

fixed my issue

Is this bug?

**Comment by samson0v** [comment]
Hi Dhaval Dalvadi, you have to use:
customerId=CustomerId("CUSTOMER","bcba4d70-e778-11eb-93f6-e9c8947e0202")
rest_client.get_attributes(entity_id=customerId,kwargs={"keys":"asdf"})
because argument kwargs type is dict, not str.
