### ISSUE TITLE
get_timeseries(...) returns an empty dict

### ISSUE THREAD

**Issue by cc-robbre** [thingsboard/thingsboard-python-rest-client#163]
Hi,

I'm trying to implement a small script which exports the timeseries data into JSON files by device name (I'm trying to print it first).
The device list is created by the `get_entities(...)` function of the REST client, which works fine for my use case.
Example:
```
page = 0
entity_list = rest_client.get_entities(EntityGroupId(ENTITY_GROUP_ID, "ENTITY_GROUP"), 100, page)
device_list = entity_list.to_dict()["data"]
```
The list above contains a list of `id: {id: "entity-id", entity_type: "DEVICE"}, name: "device-name"`.
After that step, I tried to invoke the `get_timeseries(...)` function with the following parameters:

```
for device in device_list:
      timeseries = rest_client.get_timeseries(entity_id=EntityId(device["id"]["id"],
                                                                          device["id"]["entity_type"]),
                                                       keys="keys separated with comma",
                                                       start_ts=int((time() - 604800) * 1000),
                                                       end_ts=int(time() * 1000),
                                                       use_strict_data_types=False,
                                                       limit=100)
     print(timeseries) ## this prints an empty dict {} :-(
```
The same request an HTTP-REST using `curl` call with the same user and its token works fine. 

Any suggestions on what could be wrong in this case?

Python 3.11.9 (Windows), RestClient: thingsboard-python-rest-client release/3.7.0

**Comment by samson0v** [comment]
Hi @cc-robbre, thanks for your interest in Python rest client!
I tried to reproduce your problem and in my case, everything works fine.
From your code, I can see that you are using keys parameter incorrectly. You have to specified all telemetry keys that you want to received (in your case "keys separated with comma" 😅).

My example:
```python
rest_client.login(username=username, password=password)

            device_list = rest_client.get_tenant_devices(15, 0)
            device_list = device_list.to_dict()['data']

            for device in device_list:
                timeseries = rest_client.get_timeseries(entity_id=EntityId(device["id"]["id"],
                                                                           device["id"]["entity_type"]),
                                                        keys="smm",
                                                        start_ts=0,
                                                        end_ts=int(time() * 1000),
                                                        use_strict_data_types=False,
                                                        limit=100)
                print(timeseries)
```

Result:
![image](https://github.com/user-attachments/assets/8cbdbda5-c798-4f38-83ac-3afd3f1dec63)

**Comment by cc-robbre** [comment]
Hi @samson0v,

Thanks for your reply. I've managed to get it work by using the client in normal synchronous call

I forget to mention that the empty dict only occurs if I put it inside an async function. In my case I plan to retrieve the data using python REST Client and provide it as an API path
