### ISSUE TITLE
Documentation issue 

### ISSUE THREAD

**Issue by aopetrov86** [thingsboard/thingsboard-python-rest-client#19]
`pip3 install tb-rest-client` in [Python REST Client docs](https://thingsboard.io/docs/reference/python-rest-client/) and [README](https://github.com/thingsboard/python_tb_rest_client/blob/a6cd17ef4de31f68c3226b7a9835292fbac4b1fa/README.md) installs tb-rest-client with version up to 1.1.0: https://pypi.org/project/tb-rest-client/#history . 
Meanwhile `pip3 install tb-rest-client32` installs versions 1.1 or 1.2: https://pypi.org/project/tb-rest-client32/#history. 
Which version of `pip install ...` is correct? 
Do you support tb-rest-client32 too?

**Comment by samson0v** [comment]
Hi @aopetrov86, 
> **Which version of pip install ... is correct?**
If you want to use the newest version you should use ```pip install tb-rest-client```


> **Do you support tb-rest-client32 too?**
No, tb-rest-client32 is only using for ThingsBoard v. 3.2.
