### ISSUE TITLE
get_tenant_devices devices returns object <class 'AttributeError'>

### ISSUE THREAD

**Issue by bse-sja** [thingsboard/thingsboard-python-rest-client#23]
r=rest_client.get_tenant_devices()
print(type(r))
  <class 'AttributeError'>

This is also true for get_device_by_id but get_device_credentials_by_device_id works ok.

**Comment by samson0v** [comment]
Hi @bse-sja, your issue was fixed, please update the rest-client to the latest version via the master branch.
