### ISSUE TITLE
Cannot import 'EntityId' from partially initialized module

### ISSUE THREAD

**Issue by JacksonBowe** [thingsboard/thingsboard-python-rest-client#28]
Hi,

I've just imported the tb-rest-client on a fresh virtual environment and attempted to run it. 
`import logging`
`from tb_rest_client.rest_client_pe import *`

I get the following error:
`ImportError: cannot import name 'EntityId' from partially initialized module 'tb_rest_client.models.models_ce' (most likely due to a circular import)`

from the file 
`\env\lib\site-packages\tb_rest_client\models\models_ce\__init__.py`

Are there additional prerequisite steps that I need to take for this to work?

Cheers

**Comment by JacksonBowe** [comment]
I've drilled into the error more and found it originates from this line in _admin_settings.py_

`from . import EntityId`

If I change this to 

`from .entity_id import EntityId`

I can get past the origional issue.

I then get the following error:
`Traceback (most recent call last):`
  `File "c:/Users/path_to_file", line 2, in <module>
    from tb_rest_client.rest_client_pe import *`
  `File "C:\Users\path_to_file\env\lib\site-packages\tb_rest_client\rest_client_pe.py", line 26, in <module>
    class RestClientPE(RestClientBase):`
  `File "C:\Users\path_to_file\env\lib\site-packages\tb_rest_client\rest_client_pe.py", line 331, in RestClientPE
    def load_user_group_permission_infos(self, body: list[GroupPermission]):`
`TypeError: 'type' object is not subscriptable`

**Comment by JacksonBowe** [comment]
I solved my issue. It was annoying.

Steps to solve:

1. In file: _admin_settings_id.py_ **line 17** change `from . import EntityId` to `from .entity_id import EntityId`
2. In file: _rest_client_pe.py_ change all instances of `list[str]` to `"list[str]"`
3. In file: _rest_client_ce.py_ do the same as Step 2.


Going to leave this open for a few days for visability. If possible can some feedback be added here when possible.

Cheers

**Comment by zbeacon** [comment]
Hi @JacksonBowe ,

Thank you for your participating, we were used the new generator for REST client and it is really new, so it may produce some issues. We will fix this issue in the client as soon as possible. Thanks.
