### ISSUE TITLE
handle_two_way_device_rpc_request_v1 fails when trying to call rpc_v_2_controller

### ISSUE THREAD

**Issue by IrianGT** [thingsboard/thingsboard-python-rest-client#37]
Hello, 

When trying to implement an rpc request with the sdk, I got the following error:

```
> return self.rpc_v_2_controller.handle_two_way_device_rpc_request_using_post1(body=body, device_id=device_id)
E AttributeError: 'TBClient' object has no attribute 'rpc_v_2_controller'
```
TBclient is a custom class that inherits from RestClientPE

In ret_client_base.py, the method  `handle_two_way_device_rpc_request_v1` use the the controller `rpc_v_2_controller` : 

```
def handle_two_way_device_rpc_request_v1(self, body: str, device_id: DeviceId):
    device_id = self.get_id(device_id)
    return self.rpc_v_2_controller.handle_two_way_device_rpc_request_using_post1(body=body, device_id=device_id)
```

yet the rpc_v_2_controller is initialized as follow in rest_client_base.py l.908: 

`self.rpc_v2_controller = RpcV2ControllerApi(self.api_client)`

It seems that a '_' has appeared magically in : 
`return self.rpc_v_2_controller.handle_two_way_device_rpc_request_using_post1(body=body, device_id=device_id)` ?  
Is it a bug or did I miss something important ? 

Thank you for your help !

**Comment by zbeacon** [comment]
HI ,

Please try to use the version from the master branch.

**Comment by IrianGT** [comment]
It works  ! Perfect ! Thank you !
