### ISSUE TITLE
[Feature Request] Access raw json of requests instead of Object form

### ISSUE THREAD

**Issue by JacksonBowe** [thingsboard/thingsboard-python-rest-client#41]
When using the rest client, is it possible to just have the commands return raw json? The client is extremely hard to use because an Object Oriented approach has been forced into it, which results in more complex code to extract usable information. Take the following process:
I want to get all my data converters and iterate over them
```
converters = rest_client.get_converters("1000","0")
for idx, converter in enumerate(converters['data']):
   pass

# Fails with error
# TypeError: 'PageDataConverter' object is not subscriptable
```
The above code **will not work**. This is because the rest client converts the default json response into an object `PageDataConverter`.

I'm not sure why this needs to be an object. It's just a json response from the server, which should be really easy to work with. Instead for every single request I need to add this function.
```
def toJson(input):
    return ast.literal_eval(str(input))

converters = toJson(rest_client.get_converters("1000","0"))
for idx, converter in enumerate(converters['data']):
   pass

# Works
```

Can we just have access to the raw response?

**Comment by samson0v** [comment]
Hi @JacksonBowe, it is not a dictionary, it is an obj class.
Try to use it:
```
with RestClientPE(base_url=url) as rest_client:
    try:
        # Auth with credentials
        rest_client.login(username=username, password=password)
        user = rest_client.get_user()

        converters = rest_client.get_converters("1000", "0")

        for index, item in enumerate(converters.data):
            print(index, item)

    except ApiException as e:
        logging.exception(e)
```

<img width="601" alt="зображення" src="https://user-images.githubusercontent.com/43861229/142879084-8ca075fb-5752-44e9-b351-61e709d22ed2.png">
