### ISSUE TITLE
token is not saved into token_info

### ISSUE THREAD

**Issue by fargiolas** [thingsboard/thingsboard-python-rest-client#43]
It seems that `token_info` is never filled with the actual token (guess it should be at login, shouldn't it?).
So `get_token()` always returns an empty string. Is this the expected behaviour?

**Comment by samson0v** [comment]
@fargiolas, it seems that the swagger code generator has an issue with it, I fixed it.
Thanks for your interest in ThingsBoard Python Rest Client!
