### ISSUE TITLE
AttributeError: 'RestClientCE' object has no attribute 'entity_query_controller'

### ISSUE THREAD

**Issue by freebooterish** [thingsboard/thingsboard-python-rest-client#44]
When I try the example: Count entities using Entity Data Query API, it report a error: tb_rest_client/rest_client_ce.py", line 1228, in count_entities_by_query AttributeError: 'RestClientCE' object has no attribute 'entity_query_controller'

Thanks.

**Comment by lazaj** [comment]
Same error, any advices ?

**Comment by samson0v** [comment]
Hi @freebooterish and @lazaj, it seems that you forgot to firstly use the login method or you are using the old version.
