### ISSUE TITLE
there is no public login method

### ISSUE THREAD

**Issue by fargiolas** [thingsboard/thingsboard-python-rest-client#45]
Hi, I recently discovered that the REST Api allows public login with a request on `api/auth/login/public` with a payload `{publicId: my-public-customer-id}`.

Then I can query assets, devices and timeseries using my public customer id.

Is there a way to do this from `tb-rest-client`? it shouldn't be that hard, something like this should work:

    def public_login(self, publicId):
            token_json = post(self.base_url + "/api/auth/login/public", json={"publicId": publicId},
                              verify=self.configuration.verify_ssl).json()
            token = None
            if isinstance(token_json, dict) and token_json.get("token") is not None:
                token = token_json["token"]
            self.configuration.api_key_prefix["X-Authorization"] = "Bearer"
            self.configuration.api_key["X-Authorization"] = token
            self.token_info['token'] = token

            self.api_client = ApiClient(self.configuration)
            self.load_controllers()

I could open a pull request if there's any interest... not sure if missing `username` and `password` would upset anything in RestClientBase though.

**Comment by samson0v** [comment]
Hi @fargiolas, it will be nice if you prepare a pull request for this feature.
Thanks for your interest in ThingsBoard Python Rest Client!

**Comment by fargiolas** [comment]
> Hi @fargiolas, it will be nice if you prepare a pull request for this feature. Thanks for your interest in ThingsBoard Python Rest Client!

Hey @samson0v, I'm sorry but I had no time to look at this in the past few days, but I've seen you went ahead and implemented it yourself. Thank you! really happy to see this feature in master!
