### ISSUE TITLE
New release anytime soon?

### ISSUE THREAD

**Issue by eeitnn** [thingsboard/thingsboard-python-rest-client#54]
Hi,

I'm using the rest-client in some of my azure-functions.
Unfortunately the newly added token-login method is not part of the most recent pypi-package.
Are there any plans to publish the latest code to pypi anytime soon or can you suggest a workaround?

**Comment by samson0v** [comment]
Hi @eeitnn, 

> By the way, there is some inconsistency in rest_client_base.py regarding "refresh_token" vs. "refreshToken" leading to a key-error.

This bug was fixed.


> btw, why did you remove the method "get_user_assets"? Its documented in the latest swagger doc , so it should be available in the rest-client, shouldn't it? see: [https://cloud.thingsboard.io/swagger-ui/#/asset-controller/getUserAssetsUsingGET](url)

This method still available in PE version but not in CE.
