### ISSUE TITLE
[SelfHosted]RestClientCE no attribute 'auth_controller' TB version 3.3.4, TB-Client versin 1.3.2

### ISSUE THREAD

**Issue by Daoma1** [thingsboard/thingsboard-python-rest-client#57]
Having a error using scripts from official documentation.

`
OS: Windows 10 
Python: 3.10.1
`

```
Traceback (most recent call last):
  File "D:\Python projecs\pythonProject\main.py", line 37, in <module>
    user = rest_client.get_user()
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\tb_rest_client\rest_client_ce.py", line 316, in get_user
    return self.auth_controller.get_user_using_get()
AttributeError: 'RestClientCE' object has no attribute 'auth_controller'
```

Some times get error with ssl certification 
`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)`

When I start script sever die for 30-45mins

**Comment by medutySMST** [comment]
having the same issue. 

Additionally rest_client.login(username=username, password=password) freezes the script.

**Comment by Daoma1** [comment]
`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)`
Resolved with changing ssl certificate to chain certificate. Site used for checks [https://www.sslshopper.com/ssl-checker.html](https://www.sslshopper.com/ssl-checker.html) of certificates 

'auth_controller' still returns same error as said above, but doesn't kill server.

**Comment by samson0v** [comment]
Hi @Daoma1, update your rest client to the newest version via the master branch and let us know if it helps.
