### ISSUE TITLE
bug: EntityGroupId model does not fit api response

### ISSUE THREAD

**Issue by JuliusHarald** [thingsboard/thingsboard-python-rest-client#70]
Hi,

while working with `RestClientPE` I used the method `get_entity_groups_by_type("DEVICE")`, as a result I received a list with this:
`AttributeError("module 'tb_rest_client.models.models_ce' has no attribute 'EntityGroupId'")`

When I started to look into it with the debugger I discovered, that the error happens in `api_client.py` in the method  `def __deserialize(self, data, klass): `. 

My guess is that the API send back this response:

```
[
  {
    "id": {
      "entityType": "ENTITY_GROUP",
      "id": "---"
    },
    "createdTime": 1648113081174,
    "type": "DEVICE",
    "name": "All",
    "ownerId": {
      "entityType": "TENANT",
      "id": "---"
    },
    "additionalInfo": null,
    "configuration": {
      "columns": [
        {
          "type": "ENTITY_FIELD",
          "key": "created_time",
          "sortOrder": "DESC"
        },
...
```

but in the entity_group_id model there is no field `entityType` only `id` , so this does not fit and provoke the error

**Comment by samson0v** [comment]
Hi @JuliusHarald, what version of the rest client and ThingsBoard you are using?

**Comment by JuliusHarald** [comment]
> Hi @JuliusHarald, what version of the rest client and ThingsBoard you are using?

Hi @samson0v I am using Version 1.4

**Comment by imbeacon** [comment]
Hi @JuliusHarald ,

Please try to import EntityGroupId from tb_rest_client.models.models_pe like `from tb_rest_client.models.models_pe import EntityGroupId`.

**Comment by JuliusHarald** [comment]
Hi @imbeacon ,

I do that, my code is something like:
```
            from tb_rest_client import RestClientPE
            from tb_rest_client.models.models_pe import EntityGroupId
           
           ...

           with RestClientPE(base_url=url) as rest_client:
                rest_client.login(username=username, password=password)
                device_group_info_list = rest_client.get_entity_groups_by_type("DEVICE")

```

and the `device_group_info_list` looks like this:
`[AttributeError("module 'tb_rest_client.models.models_ce' has no attribute 'EntityGroupId'"), AttributeError("module 'tb_rest_client.models.models_ce' has no attribute 'EntityGroupId'"), AttributeError("module 'tb_rest_client.models.models_ce' has no attribute 'EntityGroupId'")]
`

**Comment by imbeacon** [comment]
@JuliusHarald It looks like something wrong in the rest client with deserialisation of the response, we will investigate and fix it.

**Comment by imbeacon** [comment]
@JuliusHarald Please try to use the version from the master branch.

**Comment by JuliusHarald** [comment]
Yes, it is better, I get a result back with the group information.
But unfortunately one of the most important information is "id" and there I get this message: 
` 'id': TypeError("__init__() got an unexpected keyword argument 'entity_type'"),`

Full Output of one group:
`{'additional_info': None,
 'configuration': {'actions': {},
                   'columns': [{'key': 'created_time',
                                'sortOrder': 'DESC',
                                'type': 'ENTITY_FIELD'},
                               {'key': 'name',
                                'sortOrder': 'NONE',
                                'type': 'ENTITY_FIELD'},
                               {'key': 'device_profile',
                                'sortOrder': 'NONE',
                                'type': 'ENTITY_FIELD'},
                               {'key': 'label',
                                'sortOrder': 'NONE',
                                'type': 'ENTITY_FIELD'}],
                   'settings': {}},
 'created_time': 1648113081174,
 'edge_group_all': False,
 'external_id': None,
 'group_all': True,
 'id': TypeError("__init__() got an unexpected keyword argument 'entity_type'"),
 'name': 'All',
 'owner_id': {'entity_type': 'TENANT',
              'id': '---'},
 'owner_ids': [{'entity_type': 'TENANT',
                'id': '---f'}],
 'type': 'DEVICE'},`
