### ISSUE TITLE
[BUG] entity group controller get_entities module 'tb_rest_client.models.models_ce' has no attribute 'ShortEntityView'

### ISSUE THREAD

**Issue by ianog-eng** [thingsboard/thingsboard-python-rest-client#76]
**Describe the bug**
* the `get_entities` call returns the error `module 'tb_rest_client.models.models_ce' has no attribute 'ShortEntityView'` May be related to #75 

**Your Server Environment**
* cloud.thingsboard.io

**Your Client Environment**
* tb_rest_client-1.4-py3.7
* OS: Amazon Linux

**To Reproduce**

1. Log in to the rest client 'rest_client_tb.login(username=credentials["user"], password=credentials["password"])'
2. Call the function:
```
res = rest_client_tb.get_entities(entity_group_id = "XXXXXXXXXXXXXXXXXXXXXXXXXXX",page_size="500", page="0", sort_property = 'name', sort_order = 'ASC')
log_TB.debug("get group devices result: \n%s", str(res))
```
3. Observe the result:
```
2022-08-11 15:29:12,761    DEBUG __main__.Thingsboard | get group devices result: 
module 'tb_rest_client.models.models_ce' has no attribute 'ShortEntityView'
```

**Expected behavior**
I expect the result to be a list of groups like so (from Postman):
```
{
    "data": [
        {
            "id": {
                "entityType": "DEVICE",
                "id": "XXXXXXXXXXXXXXXXXXXXXXXXXXX"
            },
            "name": "12E22WT002",
            "created_time": "1649324729839",
            "name": "12E22WT002",
            "device_profile": "Motive.Li",
            "label": "Merlog_WT(4)"
        },
...
        {
            "id": {
                "entityType": "DEVICE",
                "id": "XXXXXXXXXXXXXXXXXXXXXXXXXXX"
            },
            "name": "02H33ESR006",
            "created_time": "1649103598563",
            "name": "02H33ESR006",
            "device_profile": "Motive.Li",
            "label": "Boxer Polokwane ESR 6"
        }
    ],
    "totalPages": 29,
    "totalElements": 283,
    "hasNext": true
}
```

**Comment by samson0v** [comment]
Hi @ianog-eng, we know about this problem but the bug is on the ThingsBoard side.
You can see from swagger that ThingsBoard return the following response:
<img width="795" alt="зображення" src="https://user-images.githubusercontent.com/43861229/184302336-2d52c55a-c785-414e-b67a-30777bb73a18.png">
created_time and other one field are in snake_case that's why the client can't deserialise data.

So we wait for when the ThingsBoard team fixes this bug.
