### ISSUE TITLE
Bug in example_application.py 

### ISSUE THREAD

**Issue by vcmorini** [thingsboard/thingsboard-python-rest-client#8]
Hello together,
When running the example_application.py I have the following traceback:

```
2020-12-20 16:28:09 - INFO - test - 57 -  Device was created:
AttributeError("'str' object has no attribute 'swagger_types'")

Traceback (most recent call last):
  File "C:/Users/vcmorini/Anaconda3/envs/iot/Lib/site-packages/tb_rest_client/models/models_ce/test.py", line 60, in <module>
    relation = EntityRelation(_from=asset.id, to=device.id, type="Contains")
AttributeError: 'AttributeError' object has no attribute 'id'
```

The error occurs in this line:
`device = rest_client.save_device(device)
`
Any suggestions?

**Comment by zbeacon** [comment]
Hi @vcmorini ,

Please tell more about your environment - Which version of the REST client, you use? And what the version of ThingsBoard you use?

**Comment by girish-d** [comment]
Hi @zbeacon ,

I too came across this issue. This is using the latest REST client (installed via pip today) and TB CE 3.2.0. 

I did some digging around and it seems in api_client.py `__deserialize()` the `found_class.attribute_map.values()` don't match the `data.keys()` coming from the server. These are the values I get:

Attrribute Map Values: ['additionalInfo', 'createdTime', 'customerId', 'id', 'label', 'name', 'tenantId', 'type']
Data Keys: ['id', 'createdTime', 'additionalInfo', 'tenantId', 'customerId', 'name', 'type', 'label', 'deviceProfileId', 'deviceData']

What would be the best way to go forward?

**Comment by vcmorini** [comment]
Hi @zbeacon ,
The device is created on the dashboard via `Device(...)`, but a bug occurs in the response of the function: `rest_client.save_device(...)`
Therefore I cannot create relations/associations with it. Example: 
![image](https://user-images.githubusercontent.com/44900293/104844425-6b34db00-58d0-11eb-8bd4-2b8bd5a5789a.png)

![image](https://user-images.githubusercontent.com/44900293/104844446-8869a980-58d0-11eb-88ac-b2be005b6a82.png)


#### Problem:
![image](https://user-images.githubusercontent.com/44900293/104844294-c6b29900-58cf-11eb-8cd7-4bd2bd157131.png)

#### Environment:
thingsboard-3.2.deb
Python 3.7
tb-rest-client 1.1.0

#### Code:
```
import logging
# Importing models and REST client class from Community Edition version
from tb_rest_client.rest_client_ce import *
from tb_rest_client.rest import ApiException
import random

logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(module)s - %(lineno)d - %(message)s',
                    datefmt='%Y-%m-%d %H:%M:%S')


rnd = random.randint(0, 999)


# ThingsBoard REST API URL
url = "XXXXXXXXXXXXXXXX:8080"

# Default Tenant Administrator credentials
username = "tenant@thingsboard.org"
password = "tenant"


# Creating the REST client object with context manager to get auto token refresh
with RestClientCE(base_url=url) as rest_client:
    try:
        # Auth with credentials
        rest_client.login(username=username, password=password)

        # Creating Customer
        customer_name = f"Customer {rnd}"
        new_customer = Customer(title=customer_name, additional_info=None, address=None, address2=None, city=None, country=None, created_time=None, email=None, id=None, name=None, phone=None, state=None, tenant_id=None, zip=None)
        new_customer_saved = rest_client.save_customer(new_customer)
        logging.info("Customer was created:\n%r\n", new_customer_saved)

        # Creating an Asset
        asset_name = f"Building {rnd}"
        new_asset = Asset(name=asset_name, type="restaurant_children", additional_info=None, created_time=None, customer_id=new_customer_saved.id, id=None, label=None, tenant_id=None)
        new_asset_saved = rest_client.save_asset(new_asset)
        logging.info("Asset was created:\n%r\n", new_asset_saved)

        # Creating relations from device to asset
        client_asset_relation = EntityRelation(_from=new_customer_saved.id, to=new_asset_saved.id, type="Contains")
        client_asset_relation_saved = rest_client.save_relation(client_asset_relation)
        logging.info(" Relation was created:\n%r\n", client_asset_relation_saved)

        # creating a Device
        device_name = f"Restaurant {rnd}"
        new_device = Device(name=device_name, type="restaurant_device_profile", additional_info=None, created_time=None, customer_id=new_customer_saved.id, id=None, label=None, tenant_id=None)
        new_device_saved = rest_client.save_device(new_device)
        logging.info(" Device was created:\n%r\n", new_device_saved)

        # Creating relations from device to asset
        asset_device_relation = EntityRelation(_from=new_asset_saved.id, to=new_device_saved.id, type="Contains")
        asset_device_relation_saved = rest_client.save_relation(asset_device_relation)
        logging.info(" Relation was created:\n%r\n", asset_device_relation_saved)

        # creating a Device
        device_name = f"Table {rnd}"
        new_device = Device(name=device_name, type="table_device_profile", additional_info=None, created_time=None, customer_id=new_customer_saved.id, id=None, label=None, tenant_id=None)
        new_device_saved = rest_client.save_device(new_device)
        logging.info(" Device was created:\n%r\n", new_device_saved)

        # Creating relations from device to asset
        asset_device_relation = EntityRelation(_from=new_asset_saved.id, to=new_device_saved.id, type="Contains")
        asset_device_relation_saved = rest_client.save_relation(asset_device_relation)
        logging.info(" Relation was created:\n%r\n", asset_device_relation_saved)

    except ApiException as e:
        logging.exception(e)
```

**Comment by samiralavi** [comment]
I have faced the same issue.

**Comment by Shawnshank** [comment]
Hi,

The problems is that your rest client has poor compatability with the API for Thingsboard version 3.2.

This should be mitigated by updating the tb-rest-client version to 1.2.
`pip3 install tb-rest-client32`
or from branch
https://github.com/thingsboard/python_tb_rest_client/tree/release/3.2

You will need to update your code from 
`from tb_rest_client.rest_client_ce import *`
`from tb_rest_client.rest import ApiException`
to
`from tb_rest_client32.rest_client_ce import * `
`from tb_rest_client32.rest import ApiException`
to use the updated rest client.

Hope this helps!

**Comment by dhaval2017** [comment]
I am able to print the Customer Id 
{'entityType': 'CUSTOMER', 'id': 'fa04f1e0-bba8-11eb-8fb6-fdd06f5a6a07'}

but getting below exception when try to get customer_assets

Traceback (most recent call last):
  File "d:\Dhaval\NistantriTech\test.py", line 39, in <module>
    results=rest_client.get_customer_assets(customer_id=customer["id"]);
  File "C:\Users\dalwa\AppData\Local\Programs\Python\Python39\lib\site-packages\tb_rest_client32\rest_client_base.py", line 109, in get_customer_assets
    return self.asset_controller.get_customer_assets_using_get(customer_id.id, str(page_size), str(page), **kwargs)
AttributeError: 'dict' object has no attribute 'id'


Here is my code

import logging
# Importing models and REST client class from Community Edition version
from tb_rest_client32.rest_client_ce import *

# Importing the API exception
from tb_rest_client32.rest import ApiException

logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(module)s - %(lineno)d - %(message)s',
                    datefmt='%Y-%m-%d %H:%M:%S')

# ThingsBoard REST API URL
url = "http://localhost:8080"
# Default Tenant Administrator credentials
username = "tenant@thingsboard.org"
password = "tenant"


with RestClientCE(base_url=url) as rest_client:
    try:
        # Auth with credentials
        rest_client.login(username=username, password=password);

        has_next=True;
        customer_list=[];
        members_list=[];
        
        while(has_next):
            results=rest_client.get_customers()
            customer_list.extend(results["data"]);
            has_next=results["hasNext"];
        logging.info("Customers: \n%r\n",customer_list);

        for idx, customer in enumerate(customer_list):
            print(customer["id"]);
            has_next=True;
            member_list=[];
            while(has_next):
                results=rest_client.get_customer_assets(customer_id=customer["id"]);
                member_list.append(results["data"]);
                has_next=results["hasNext"];
    except ApiException as e:
        logging.exception(e)

**Comment by dhaval2017** [comment]
Still having same issue
I am able to print the Customer Id 
{'entityType': 'CUSTOMER', 'id': 'fa04f1e0-bba8-11eb-8fb6-fdd06f5a6a07'}

but getting below exception when try to get customer_assets

Traceback (most recent call last):
  File "d:\Dhaval\NistantriTech\test.py", line 39, in <module>
    results=rest_client.get_customer_assets(customer_id=customer["id"]);
  File "C:\Users\dalwa\AppData\Local\Programs\Python\Python39\lib\site-packages\tb_rest_client32\rest_client_base.py", line 109, in get_customer_assets
    return self.asset_controller.get_customer_assets_using_get(customer_id.id, str(page_size), str(page), **kwargs)
AttributeError: 'dict' object has no attribute 'id'


Here is my code


`import logging
from tb_rest_client32.rest_client_ce import *
from tb_rest_client32.rest import ApiException
logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(module)s - %(lineno)d - %(message)s',
                    datefmt='%Y-%m-%d %H:%M:%S')
url = "http://localhost:8080"
username = "tenant@thingsboard.org"
password = "tenant"
with RestClientCE(base_url=url) as rest_client:
    try:
        rest_client.login(username=username, password=password);
        has_next=True;
        customer_list=[];
        members_list=[];       
        while(has_next):
            results=rest_client.get_customers()
            customer_list.extend(results["data"]);
            has_next=results["hasNext"];
        logging.info("Customers: \n%r\n",customer_list);
        for idx, customer in enumerate(customer_list):
            print(customer["id"]);
            has_next=True;
            member_list=[];
            while(has_next):
                results=rest_client.get_customer_assets(customer_id=customer["id"]);
                member_list.append(results["data"]);
                has_next=results["hasNext"];
    except ApiException as e:
        logging.exception(e)
`
