### ISSUE TITLE
SYS_ADMIN cannot add customer to tenant via API

### ISSUE THREAD

**Issue by cchildress-gsu** [thingsboard/thingsboard-python-rest-client#87]
When attempting to add a customer to a tenant, the python client returns the following: 

{"status":403,"message":"You don\'t have permission to perform this operation!","errorCode":20,"timestamp":"2022-10-13T19:14:48.157+00:00"}

Does a SYS_ADMIN user have all permissions?

**Comment by samson0v** [comment]
Hi @cchildress-gsu, the sysadmin can't add customers, only the tenant can add customers.
