### ISSUE TITLE
Customers Model has unnecessary mandatory fields

### ISSUE THREAD

**Issue by Butanding** [thingsboard/thingsboard-python-rest-client#89]
Current Release 1.4:
Customer's Model has Mandatory fields, that are not necessary. For example: phone, address, address2 and many more.

In version 1.3.2 this field was not mandatory. But in Version 1.3.2 it got mandatory as well as in Version 1.4.

Now if you download a Customer, that was created through the UI or another REST API Interface but without the unnecessary mandatory field (e.g. phone). Then the Python SDK will throw an exception and invalidate the Object.

In the current Master Branch, these fields are not mandatory anymore. But the current Master Branch is not released (yet). Can you please release the current master branch?

Until that, one can use the version 1.3.2 (that version has some other disadvantages).

Thanks.

**Comment by samson0v** [comment]
Hi @Butanding, you can use the master version (this bug was fixed) for now. We will release a new version in the nearest future.
