### ISSUE TITLE
create a Device object need a not None attribute "device_profile_id"

### ISSUE THREAD

**Issue by AWSDJIKL** [thingsboard/thingsboard-python-rest-client#97]
When I want to use rest_client.save_device() method to register a new device, I need to new a Device object. But the init method need a attribute "device_profile_id". What should I provide?

**Comment by imbeacon** [comment]
Hi @AWSDJIKL ,

You should use device profile id that you want to use with this device (Device profile name is equal to your device type).

**Comment by samson0v** [comment]
@AWSDJIKL, any updates? Can we close the issue?
